export function createArray() {
  const notificationArray = [
    {
      name: "Mark webber",
      posterImage: "/assets/images/avatar-mark-webber.webp",
      action: "reacted to your recent post",
      group: "My first tournament today!",
      unread: true,
      time: "1m ago",
      message: "",
      picture: "",
    },
    {
      name: "Angela Gray",
      posterImage: "/assets/images/avatar-angela-gray.webp",
      action: "followed you",
      group: "",
      unread: true,
      time: "5m ago",
      message: "",
      picture: "",
    },
    {
      name: "Jacob Thompson",
      posterImage: "/assets/images/avatar-jacob-thompson.webp",
      action: "Has joined your group",
      group: "Chess Club",
      unread: true,
      time: "1 day ago",
      message: "",
      picture: "",
    },
    {
      name: "Rizky Hasanuddin",
      posterImage: "/assets/images/avatar-rizky-hasanuddin.webp",
      action: "sent you a private message",
      group: "",
      unread: false,
      time: "5 days ago",
      message:
        "Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and I'm already having lots of fun and improving my game.",
      picture: "",
    },
    {
      name: "Kimberly Smith",
      posterImage: "/assets/images/avatar-kimberly-smith.webp",
      action: "commented on your picture",
      group: "Pic Club",
      unread: false,
      time: "1 week ago",
      message: "",
      picture: "/assets/images/image-chess.webp",
    },
    {
      name: "Nathan Peterson",
      posterImage: "assets/images/avatar-nathan-peterson.webp",
      action: "reacted to your recent post",
      group: "5 end-game strategies to increase your win rate",
      unread: true,
      time: "2 weeks ago",
      message: "",
      picture: "",
    },
    {
      name: "Anna Kim",
      posterImage: "assets/images/avatar-anna-kim.webp",
      action: "left the group",
      group: "Chess Club",
      unread: false,
      time: "2 weeks ago",
      message: "",
      picture: "",
    },
  ];

  return notificationArray;
}
